1649006000.1845508: An error ocurrer during the game
Traceback (most recent call last):
  File "/home/slimbook/Documentos/Repositories/MotorRol/samples/cli_enhanced/../../engine/engine.py", line 139, in run
    end = self.manage_pause_menu(pj, action)
  File "/home/slimbook/Documentos/Repositories/MotorRol/samples/cli_enhanced/../../engine/engine.py", line 95, in manage_pause_menu
    self.saveGame()
  File "/home/slimbook/Documentos/Repositories/MotorRol/samples/cli_enhanced/../../engine/engine.py", line 79, in saveGame
    with lzma.open(filename, 'wb') as f:
  File "/usr/lib/python3.10/lzma.py", line 309, in open
    binary_file = LZMAFile(filename, lz_mode, format=format, check=check,
  File "/usr/lib/python3.10/lzma.py", line 120, in __init__
    self._fp = builtins.open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'saves/Unnamed_030422_191320.xz'

Aborting the game execution